version: '3.7'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Web interface port
    labels:
      - "name=rabbitmq"
